version: "3.9"

services:
  # === Local LLaMA model service ===
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   environment:
  #     - OLLAMA_MODELS=llama3
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - llm_net

  # === Flask + Vosk + Piper voice server ===
  voice_server:
    build:
      context: .
      dockerfile: Dockerfile.voice
    container_name: voice-server
    restart: unless-stopped
    # depends_on:
    #   - ollama
    networks:
      - llm_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
      - NGROK_DOMAIN=${NGROK_DOMAIN}
      - REPLY_LANG=auto
      - WHISPER_MODEL=large
      - WHISPER_DEVICE=cpu
      - WHISPER_COMPUTE=int16
      - PIPER_PATH=/root/.local/share/piper/voices/ne_NP-chitwan-medium
      - PIPER_MODEL=ne_NP-chitwan-medium
      - PIPER_VOICES_DIR=/root/.local/share/piper/voices
      - PIPER_NE_MODEL=ne_NP-chitwan-medium
      - PIPER_HI_MODEL=hi_IN-rohan-medium
      - PIPER_EN_MODEL=en_US-amy-low
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: ["python3", "-u", "server.py"]

  # === Ngrok tunnel (for Twilio webhook) ===
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
    - "http"
    - "voice-server:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - voice_server
    ports:
      - "4040:4040"
    networks:
      - llm_net

# volumes:
#   ollama_data:

networks:
  llm_net:
    driver: bridge
